name: README.gsをREADME.mdに変換
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # git clone (this)
      - name: run
        run: |
          cat README.gs | sed '1d' | sed '$d' >README.md
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "shimajima-eiji"
          git add -A
          git commit -m "Update dummy by Github Actions"
          git pull
          git push
